<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>AuthService.Core</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="DirectoryService.Core" Version="1.0.0" />
      <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.11" />
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.11" />
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AuthService.Domain\AuthService.Domain.csproj" />
    </ItemGroup>

</Project>
