<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Shared.Kernel\Shared.Kernel.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    </ItemGroup>

    <PropertyGroup>
        <PackageId>DirectoryService.Core</PackageId>
        <Version>1.0.0</Version>
        <Authors>Contempl</Authors>
        <Company>Prolongisti</Company>
        <PackageDescription>Core</PackageDescription>
        <RepositoryUrl>https://github.com/contempl/DirectoryService</RepositoryUrl>
    </PropertyGroup>

</Project>
