<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>FileService.Infrastructure</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\FileService.Core\FileService.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AWSSDK.S3" Version="4.0.19" />
    </ItemGroup>

</Project>
